# Generated by Django 4.2.7 on 2023-12-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamingApp', '0002_gamemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameModel',
        ),
    ]
