# Generated by Django 4.2.7 on 2023-12-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamingApp', '0003_delete_gamemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gameImage', models.ImageField(upload_to='media/Game')),
            ],
        ),
    ]
